<?php
function esc_mod_acf_local_fields(){
    if( function_exists('acf_add_local_field_group') ):

        acf_add_local_field_group(array(
            'key' => 'group_5d164816136f2',
            'title' => 'Block : Hero',
            'fields' => array(
                array(
                    'key' => 'field_5d1b98e79f0f0',
                    'label' => 'Content',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5d1b991486ee0',
                    'label' => 'Hero Text',
                    'name' => 'hero_content',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d1b993c86ee1',
                            'label' => '',
                            'name' => 'hero_text',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5d1b9e4540b3d',
                    'label' => 'CTAs',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5d1b9cc2690ea',
                    'label' => 'Hero Button Group',
                    'name' => 'hero_button_group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d1b9d3f07200',
                            'label' => '',
                            'name' => 'button_group',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'field_5d1b9d78b8191',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5d1b66c9b1788',
                    'label' => 'Settings',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5d1b95cb10a41',
                    'label' => 'Hero Height',
                    'name' => 'hero_height',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d1b97f1d4f30',
                            'label' => '',
                            'name' => 'height',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'field_5d1b9650a529d',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5d1b960f10a42',
                    'label' => 'Hero Overlay',
                    'name' => 'hero_overlay',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d1b97c8d4f2f',
                            'label' => '',
                            'name' => 'overlay',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'field_5d1b9b985ca2c',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5d1b90f6adfcc',
                    'label' => 'Hero Background',
                    'name' => 'hero_background',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d1b66f8b1789',
                            'label' => 'Type',
                            'name' => 'type',
                            'type' => 'select',
                            'instructions' => 'Select the type of Hero Background',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'video' => 'Video Background',
                                'image' => 'Image Background',
                            ),
                            'default_value' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_5d1b903120224',
                            'label' => 'Images',
                            'name' => 'images',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d1b66f8b1789',
                                        'operator' => '==',
                                        'value' => 'image',
                                    ),
                                    array(
                                        'field' => 'field_5d1b66f8b1789',
                                        'operator' => '!=',
                                        'value' => 'video',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '70',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5d1b904e20225',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => 'Upload Background Images',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_5d1b66f8b1789',
                                                'operator' => '==',
                                                'value' => 'image',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '60',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_5d1b920ead7c8',
                            'label' => 'Videos',
                            'name' => 'videos',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d1b66f8b1789',
                                        'operator' => '==',
                                        'value' => 'video',
                                    ),
                                    array(
                                        'field' => 'field_5d1b66f8b1789',
                                        'operator' => '!=',
                                        'value' => 'image',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '70',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'block',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5d1b920ead7c9',
                                    'label' => 'Video',
                                    'name' => 'video',
                                    'type' => 'text',
                                    'instructions' => 'Upload Background Video',
                                    'required' => 1,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_5d1b66f8b1789',
                                                'operator' => '==',
                                                'value' => 'video',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '60',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d1b963a26267',
            'title' => 'Components : Reusable',
            'fields' => array(
                array(
                    'key' => 'field_5d1b9650a529d',
                    'label' => 'Height Options',
                    'name' => 'height_options',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'normal' => 'Normal',
                        'tall' => 'Tall',
                    ),
                    'default_value' => array(
                        0 => 'normal',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5d1b9d78b8191',
                    'label' => 'Button Group',
                    'name' => 'button_group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d1b9d9db8193',
                            'label' => 'Button Type',
                            'name' => 'button_type',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'no' => 'No Buttons',
                                'normal' => 'Normal',
                            ),
                            'default_value' => array(
                                0 => 'normal',
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_5d1b9d85b8192',
                            'label' => 'Button Position',
                            'name' => 'button_position',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d1b9d9db8193',
                                        'operator' => '!=',
                                        'value' => 'no',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'right' => 'Right side of the Text',
                                'left' => 'Left side of the Text',
                                'under' => 'Under the Text',
                            ),
                            'default_value' => array(
                                0 => 'under',
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_5d1b9da8b8194',
                            'label' => 'Button Link',
                            'name' => 'button_link',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d1b9d9db8193',
                                        'operator' => '!=',
                                        'value' => 'no',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5d1b9f48a0851',
                                    'label' => 'Link',
                                    'name' => 'link',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5d1b9b985ca2c',
                    'label' => 'Overlay options',
                    'name' => 'overlay_options',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'no' => 'No Overlay',
                        'white' => 'White',
                        'black' => 'Black',
                        'vertical-gradient' => 'Vertical Gradient',
                        'horizontal-gradient' => 'Horizontal Gradient',
                    ),
                    'default_value' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5d24877f14947',
                    'label' => 'Color Picker',
                    'name' => 'color_picker',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d24d4e57f4bf',
            'title' => 'Components : Semi-Custom Fonts & Font Weights',
            'fields' => array(
                array(
                    'key' => 'field_5d24d503e7c84',
                    'label' => 'Font Families',
                    'name' => 'semi_custom_fonts',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Archivo Narrow' => 'Archivo Narrow',
                        'Arvo' => 'Arvo',
                        'Cardo' => 'Cardo',
                        'Fjalla One' => 'Fjalla One',
                        'Lato' => 'Lato',
                        'Libre Baskerville' => 'Libre Baskerville',
                        'Montserrat' => 'Montserrat',
                        'Merriweather' => 'Merriweather',
                        'Noto Serif' => 'Noto Serif',
                        'Open Sans' => 'Open Sans',
                        'Open Sans Condensed' => 'Open Sans Condensed',
                        'Oswald' => 'Oswald',
                        'Old Standard TT' => 'Old Standard TT',
                        'Playfair Display' => 'Playfair Display',
                        'PT Sans' => 'PT Sans',
                        'PT Serif' => 'PT Serif',
                        'Raleway' => 'Raleway',
                        'Roboto' => 'Roboto',
                        'Roboto Condensed' => 'Roboto Condensed',
                        'Roboto Slab' => 'Roboto Slab',
                        'Source Sans Pro' => 'Source Sans Pro',
                        'Source Serif Pro' => 'Source Serif Pro',
                        'Unna' => 'Unna',
                    ),
                    'default_value' => array(
                        0 => 'Open Sans',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5d24d642ae439',
                    'label' => 'Font Weights',
                    'name' => 'semi_custom_font_weights',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        100 => 'Thin 100',
                        '100i' => 'Thin 100 italic',
                        300 => 'Light 300',
                        '300i' => 'Light 300 italic',
                        400 => 'Regular 400',
                        '400i' => 'Regular 400 italic',
                        500 => 'Medium 500',
                        '500i' => 'Medium 500 italic',
                        700 => 'Bold 700',
                        '700i' => 'Bold 700 italic',
                        900 => 'Black 900',
                        '900i' => 'Black 900 italic',
                    ),
                    'default_value' => array(
                        0 => 400,
                        1 => '400i',
                        2 => 700,
                        3 => '700i',
                    ),
                    'allow_null' => 0,
                    'multiple' => 1,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'post',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d24d238df473',
            'title' => 'Options: Font Settings',
            'fields' => array(
                array(
                    'key' => 'field_5d24d608b20a9',
                    'label' => 'Headlines (Headings & Subheadings)',
                    'name' => 'headlines_fonts',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d24d2bce6484',
                            'label' => '',
                            'name' => 'headlines_fonts_settings',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'group_5d24d4e57f4bf',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5d24d8b5a599e',
                    'label' => 'Body Text',
                    'name' => 'body_fonts',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d24d8b5a599f',
                            'label' => '',
                            'name' => 'body_fonts_settings',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'group_5d24d4e57f4bf',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5d24d958a59a1',
                    'label' => 'Buttons',
                    'name' => 'buttons_fonts',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d24d958a59a2',
                            'label' => 'Buttons',
                            'name' => 'buttons_fonts_settings',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'group_5d24d4e57f4bf',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'block',
                        'operator' => '==',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d2374ebc065a',
            'title' => 'Options: Footer Settings',
            'fields' => array(
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-footer',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d239371829d3',
            'title' => 'Options: Main Header',
            'fields' => array(
                array(
                    'key' => 'field_5d2393834aa23',
                    'label' => '',
                    'name' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-header',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d2360cc8db85',
            'title' => 'Options: Semi-Custom Theme Settings',
            'fields' => array(
                array(
                    'key' => 'field_5d24da287564c',
                    'label' => 'Font Settings',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5d24daddf703d',
                    'label' => '',
                    'name' => 'site_fonts',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d24da343b843',
                            'label' => '',
                            'name' => 'fonts_settings',
                            'type' => 'clone',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'clone' => array(
                                0 => 'group_5d24d238df473',
                            ),
                            'display' => 'seamless',
                            'layout' => 'block',
                            'prefix_label' => 0,
                            'prefix_name' => 0,
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'semi-custom-settings',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d235a85a0b43',
            'title' => 'Options: Top Header',
            'fields' => array(
                array(
                    'key' => 'field_5d23940a1e045',
                    'label' => '',
                    'name' => 'top_header_group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5d237f5d94527',
                            'label' => 'Settings',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_5d23833d7074f',
                            'label' => 'Enable/Disable Top Header',
                            'name' => 'top_header_enable',
                            'type' => 'button_group',
                            'instructions' => 'The top header will be enabled by default. Disable it by toggling the switch below.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'enable' => 'Enable',
                                'disable' => 'Disable',
                            ),
                            'allow_null' => 0,
                            'default_value' => 'enabled',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        array(
                            'key' => 'field_5d238907ab814',
                            'label' => 'Header Type',
                            'name' => 'header_type',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d23833d7074f',
                                        'operator' => '==',
                                        'value' => 'enable',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'top-header-one' => 'Top Header One',
                                'top-header-two' => 'Top Header Two',
                                'top-header-three' => 'Top Header Three',
                                'top-header-four' => 'Top Header Four',
                                'top-header-five' => 'Top Header Five',
                            ),
                            'default_value' => array(
                                0 => 'top-header-one',
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 1,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_5d23872f4ee6a',
                            'label' => 'Enable/Disable Social Media Links',
                            'name' => 'social_media_top_header',
                            'type' => 'button_group',
                            'instructions' => 'By default, social media links will be enabled on the top header.',
                            'required' => 1,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d23833d7074f',
                                        'operator' => '==',
                                        'value' => 'enable',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'enable' => 'Enable',
                                'disable' => 'Disable',
                            ),
                            'allow_null' => 0,
                            'default_value' => '',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                        ),
                        array(
                            'key' => 'field_5d238acb63baa',
                            'label' => '',
                            'name' => '',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '<h4>To edit social links, go to Semi-Custom > Social on the sidebar menu</h4>',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'field_5d238b9443e4e',
                            'label' => 'Contact Details',
                            'name' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d23833d7074f',
                                        'operator' => '==',
                                        'value' => 'enable',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_5d238c1843e50',
                            'label' => 'Email Address',
                            'name' => 'contact_email_address',
                            'type' => 'email',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d23833d7074f',
                                        'operator' => '==',
                                        'value' => 'enable',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'Please enter a valid email address.',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_5d238ba143e4f',
                            'label' => 'Phone Number',
                            'name' => 'contact_phone_number',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_5d23833d7074f',
                                        'operator' => '==',
                                        'value' => 'enable',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'Please enter a valid phone number eg: (647)XXX-XXXX',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5d238d0752f1c',
                            'label' => 'Brokerage Details',
                            'name' => 'brokerage_details',
                            'type' => 'text',
                            'instructions' => 'Please enter the name of the Broker. Leave empty if not applicable.',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '100',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-header',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5d1628d53d4c9',
            'title' => 'Page : Home - Flexible Blocks',
            'fields' => array(
                array(
                    'key' => 'field_5d16292cc6768',
                    'label' => 'Flexible Blocks',
                    'name' => 'home_flexible_blocks',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        'layout_5d16297146ed6' => array(
                            'key' => 'layout_5d16297146ed6',
                            'name' => 'hero_block',
                            'label' => 'Hero',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5d1629e421871',
                                    'label' => 'Hero Wrapper',
                                    'name' => 'hero_wrapper',
                                    'type' => 'clone',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'clone' => array(
                                        0 => 'group_5d164816136f2',
                                    ),
                                    'display' => 'seamless',
                                    'layout' => 'block',
                                    'prefix_label' => 0,
                                    'prefix_name' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => 'Add Row',
                    'min' => '',
                    'max' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/front-page.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'modified' => 1562087299,
        ));

    endif;
}

add_action('acf/init', 'esc_mod_acf_local_fields');
